services:
  - type: web
    name: flask-abstract-app
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: starter
    disk:
      name: data
      mountPath: /var/data  # ✅ must match app.py
      sizeGB: 1


