services:
  - type: web
    name: college-abstract-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
    plan: starter  # You said you're using $7/month paid plan
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
